### PR TITLE
Update ghc.nix instructions, pointing to the new home of ghc.nix

### PR DESCRIPTION
**Pull request by sgraf812**
Initialising the flake template

### CODE REVIEW

**Comment by int-index** [comment]
Thanks, but could you not assume the use of direnv?

**Comment by int-index** [comment]
Also I'm getting this error when I try the new command

```
$ nix flake init -t git+https://gitlab.haskell.org/ghc/ghc.nix
warning: redirecting to https://gitlab.haskell.org/ghc/ghc.nix.git/
fatal: not a git repository: '.'
error:
       … while fetching the input 'git+https://gitlab.haskell.org/ghc/ghc.nix'

       error: program 'git' failed with exit code 128
```

**Comment by int-index** [comment]
This worked:

```
$ nix flake init -t git+https://gitlab.haskell.org/ghc/ghc.nix.git
```

but it pollutes the repo with `.envrc` and `flake.nix`. What about

```
$ nix develop git+https://gitlab.haskell.org/ghc/ghc.nix.git -c $SHELL
```

**Comment by sgraf812** [comment]
Great idea! I added a commit that adds your suggestion.

**Pull request merged**
